money = float(input("Enter how much money you want(2dp). I will give it to you in the least amount of notes/coins. £"))

desire = money
twenties = 0
tens = 0
fives = 0
twos = 0
ones = 0
fiftyps = 0
twentyps = 0
tenps = 0
fiveps = 0
twops = 0
oneps = 0

while money != 0:
    while money >= 20:
        money -= 20
        twenties += 1
    while money < 20 and money >= 10:
        money -= 10
        tens += 1
    while money < 10 and money >= 5:
        money -= 5
        fives += 1
    while money < 5 and money >= 2:
        money -= 2
        twos += 1
    while money < 2 and money >= 1:
        money -= 1
        ones += 1
    while money < 1 and money >= 0.5:
        money -= 0.5
        fiftyps += 1
    while money < 0.5 and money >= 0.2:
        money -= 0.2
        twentyps += 1
    while money < 0.2 and money >= 0.1:
        money -= 0.1
        tenps += 1
    while money < 0.1 and money >= 0.05:
        money -= 0.05
        fiveps += 1
    while money < 0.05 and money >= 0.02:
        money -= 0.02
        twops += 1
    while money < 0.02 and money >= 0.01:
        money -= 0.01
        oneps += 1
print(f"{twenties} twenties, {tens} tens, {fives} fives, {twos} twos, {ones} ones, {fiftyps} fifty ps,{twentyps} twenty ps, {tenps} ten ps, {fiveps} five ps, {twops} two ps and {oneps} one ps make up your desired {desire}")